### ISSUE TITLE
Add to DefinitelyTyped?

### ISSUE THREAD

**Issue by Bartvds** [wizzard0/react-typescript-definitions#1]
I saw this mentioned on Twitter, maybe it is extra cool to add these to [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped)?

The typing community pools their work in the Github repos, and everything in there automatically gets redistributed on both NuGet and TSD.

It makes it easy for other people to find them and send in fixes and contributions, as DT is the main hub for typings now (we even get linked from typescriptlang.org)

**Comment by wizzard0** [comment]
Package maintenance delegated to tsd/typings teams.
