### ISSUE TITLE
Unclaim the nuget package name

### ISSUE THREAD

**Issue by basarat** [wizzard0/react-typescript-definitions#7]
@wizzard0 Hey mate can you rename your nuget package to not use the DT namespace. See : https://github.com/DefinitelyTyped/NugetAutomation/issues/14

Feel free to contact @staxmanade for any help :rose:

**Comment by wizzard0** [comment]
hmm, that's unfortunate. See the rest of the discussion at DefinitelyTyped/NugetAutomation#14 please.
